# Generated by Django 4.1.2 on 2023-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('subjectName', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
            ],
        ),
    ]
